version: '2'
services:
    node:
      build: './dronesym-node'
      ports:
        - "3000:3000"

    angular:
      build: './dronesym-frontend'
      ports:
        - "4200:4200"

    flask:
      build: './dronesym-python'
      ports:
        - "5000:5000"